Correct installation script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,23 @@
 # Usage: ./install && poetry shell
 poetry install -q
-poetry env use 3.8 -q
+
+if [ $? -eq 0 ]; then
+    echo "Successfully installed dependencies."
+else
+    echo "Failed to install dependencies."
+    exit 1
+fi
+
+PYTHON_VERSION="$(cat .python-version)"
+
+poetry env use $PYTHON_VERSION -q
+
+if [ $? -eq 0 ]; then
+    echo "Successfully set Python version to $PYTHON_VERSION."
+else
+    echo "Failed to set Python version to $PYTHON_VERSION."
+    exit 1
+fi
 
 DIR="$(dirname "$(readlink -f "$0")")"
 CMD="export PATH=\$PATH:$DIR/scripts"
